# Legal Advisory System Frontend - Netlify Configuration

[build]
  command = "npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  # VITE_API_URL will be set in Netlify dashboard environment variables
